version: "3"
services:
    libotrio:
        build: .
        ports:
            - "3000:3000"
        environment: 
            - SLACK_SIGNING_SECRET
            - SLACK_BOT_USER_OAUTH_TOKEN
            - SLACK_APP_TOKEN
            - MYSQL_HOSTNAME
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
        depends_on: 
            - database

    database:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment: 
           - MYSQL_ROOT_PASSWORD
           - MYSQL_DATABASE
           - MYSQL_USER
           - MYSQL_PASSWORD
