version: "3"
services:
  libotrio:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SLACK_BOT_USER_OAUTH_TOKEN
      - SLACK_APP_TOKEN
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOSTNAME=database
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
