name: Build & Deploy

on:
  push

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/libotrio

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ steps.tag.outputs.tag }} --label "runnumber=${GITHUB_RUN_ID}"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.ref == 'ref/head/main'
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        if: github.ref == 'ref/head/main'
        run: docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}

    outputs:
      docker_tag: ${{ steps.tag.outputs.tag }}

  deployment-prod:
    name: Deploy to Prod
    needs: build
    if: github.ref == 'ref/head/main'
    runs-on:
      - self-hosted
      - liatrio-runners-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
