name: Build & Deploy

on:
  push

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/libotrio

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate tag
        id: tag
        run: echo ::set-output name=tag::$(jq .version package.json)

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ steps.tag.outputs.tag }} --label "runnumber=${GITHUB_RUN_ID}"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}

    outputs:
      docker_tag: ${{ steps.tag.outputs.tag }}

  deployment-prod:
    name: Deploy to Prod
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on:
      - self-hosted
      - liatrio-runners-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Helm Upgrade
        run: |
          branchName=${GITHUB_REF##*/}
          helm version
          helm upgrade --install libotrio chart -n libotrio --create-namespace --set image.repository=$IMAGE_NAME --set image.tag=${{needs.build.outputs.docker_tag}}