name: Libotrio Deployment

on: push
    # branches:
    # # - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/libotrio
  # NODE_VERSION: '12.16.3'
  # TERRAGRUNT_VERSION: '0.28.14'

jobs:
    build:
      name: Tag image
      runs-on:  
      - self-hosted
      - liatrio-runners-prod
      steps:
        - uses: actions/checkout@v2

        - name: Generate tag
          id: tag
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

        
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ secrets.CR_USER }}
            password: ${{ secrets.CR_PAT }}

        - name: Generate Docker Image Metadata
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: ghcr.io/liatrio/liatrio-employee-map
            tags: |
              type=sha
              type=raw,value=latest
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Push image
          run: docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}
      outputs:
        docker_tag: ${{ steps.tag.outputs.tag }}
    libotrio-deployment-test-prod:
      name: Libotrio-Deployment-Prod

      runs-on: 
      - self-hosted
      - liatrio-runners-prod

      steps:
        # Checks out a copy of your repository on the ubuntu-latest machine
        - name: Checkout code
          uses: actions/checkout@v2