name: Libotrio Deployment

on:
  push

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/libotrio
  # NODE_VERSION: '12.16.3'
  # TERRAGRUNT_VERSION: '0.28.14'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Generate tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ steps.tag.outputs.tag }} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push image
        if: github.ref == 'ref/head/main'
        run: docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}
    outputs:
      docker_tag: ${{ steps.tag.outputs.tag }}
  deployment-prod:
    name: Deploy to Prod
    needs: build
    if: github.ref == 'ref/head/main'
    runs-on:
      - self-hosted
      - liatrio-runners-prod

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
